### https://graphql-docs-v2.opencollective.com/queries/hosts
POST https://api.opencollective.com/graphql/v2/{{$dotenv Token}}
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query (
  $limit: Int!
  $offset: Int!
  $searchTerm: String
  $tag: [String]
  $tagSearchOperator: TagSearchOperator!
  $includeArchived: Boolean
  $isActive: Boolean
  $skipRecentAccounts: Boolean
  $country: [CountryISO]
  # $height: Int
  # $format: ImageFormat
  # $height2: Int
  # $format2: ImageFormat
  # $accountType: AccountType
) {
  hosts(
    limit: $limit
    offset: $offset
    searchTerm: $searchTerm
    tag: $tag
    tagSearchOperator: $tagSearchOperator
    includeArchived: $includeArchived
    isActive: $isActive
    skipRecentAccounts: $skipRecentAccounts
    country: $country
  ) {
    offset
    limit
    totalCount
    nodes {
      id
      # legacyId
      slug
      type
      name
      # legalName
      # description
      # longDescription
      tags
      website
      twitterHandle
      githubHandle
      repositoryUrl
      currency
      # expensePolicy
      # isIncognito
      # imageUrl(height: $height, format: $format)
      # backgroundImageUrl(height: $height2, format: $format2)
      # createdAt
      # updatedAt
      isArchived
      isFrozen
      isActive
      isHost
      isAdmin
      # emails
      # settings
      # supportedExpenseTypes
      # categories
      # totalFinancialContributors(accountType: $accountType)
      # platformFeePercent
      # platformContributionAvailable
      # contributionPolicy
      # hostFeePercent
      # totalHostedCollectives
      # totalHostedAccounts
      # isOpenToApplications
      # termsUrl
      # supportedPaymentMethods
      # paypalClientId
      # supportedPayoutMethods
      # isTrustedHost
      # hasDisputedOrders
      # hasInReviewOrders
    }
  }
}

{
  "limit": 1,
  "offset": 0,
  "tagSearchOperator": "OR",
  "isActive": true
}
